-- ============================================================================
-- 0001_init.sql — Thauma operations schema (Cloudflare D1 / SQLite)
-- ============================================================================
-- Thauma is the system of record. Ministry partners (Chase Roush and anyone
-- who comes after) are TENANTS inside it, not separate systems.
--
-- Three decisions are baked into this file. They are all cheap now and
-- painful to retrofit, which is why they are here before any UI exists.
--
--   1. EVERY tenant-owned row carries partner_id.
--      Not "we'll filter in the app layer". The column is NOT NULL on every
--      table that holds partner data, so a query that forgets to scope is a
--      bug you can grep for rather than a silent data leak.
--
--   2. NO DONOR PII. EVER.
--      Donation records live in the giving platform (Donorbox et al). This
--      database stores AGGREGATES only — see goal_snapshots. There is
--      deliberately no donations table and no amount column on contacts.
--      That is not an oversight; it is the design. A partner reads their own
--      donor detail by logging into the giving platform directly.
--      Consequence: Chase cannot see another partner's donor list because it
--      is not here to see. That is a real guarantee, not a policy promise.
--
--   3. CONSENT IS PER-PURPOSE AND PER-PARTNER.
--      Giving is not newsletter consent. Someone who donated has not opted
--      into a mailing list, and someone on Chase's list has not opted into
--      Thauma's. newsletter_consent is its own column with its own source and
--      timestamp, and it is scoped to the partner like everything else.
--      GDPR applies — Croatia is in the EU and consent records are evidence.
--
-- Conventions:
--   ids          TEXT (UUIDv4/ULID), generated by the app, not the DB
--   timestamps   TEXT, ISO-8601 UTC ('2026-08-14T16:53:00Z')
--   dates        TEXT, 'YYYY-MM-DD'
--   money        INTEGER cents. Never REAL. Never floats for money.
--   booleans     INTEGER 0/1
--   enums        TEXT + CHECK constraint (SQLite has no native enum)
-- ============================================================================

PRAGMA foreign_keys = ON;


-- ============================================================================
-- PARTNERS — the tenant boundary
-- ============================================================================
CREATE TABLE partners (
  id            TEXT PRIMARY KEY,
  slug          TEXT NOT NULL UNIQUE,          -- 'chase-roush'
  display_name  TEXT NOT NULL,                 -- 'Chase Roush'
  status        TEXT NOT NULL DEFAULT 'prospective'
                  CHECK (status IN ('prospective','active','on_leave','alumni')),
  -- Where this partner's giving actually lives. We store the URL/identifier so
  -- the site can link out, never the donations themselves.
  giving_url    TEXT,
  giving_provider TEXT CHECK (giving_provider IN ('donorbox','amplify','ministrylinq','other')),
  -- Public site fields
  is_public     INTEGER NOT NULL DEFAULT 0 CHECK (is_public IN (0,1)),
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);


-- ============================================================================
-- USERS AND ACCESS
-- ============================================================================
-- global_role is ORG-level authority. Partner-level access is granted
-- separately in partner_users. An 'admin' is not automatically entitled to
-- read a partner's contacts — the UI must still go through partner_users, and
-- every such read is written to audit_log. See db/README.md.
CREATE TABLE users (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE COLLATE NOCASE,
  name          TEXT NOT NULL,
  global_role   TEXT NOT NULL DEFAULT 'staff'
                  CHECK (global_role IN ('admin','staff')),
  status        TEXT NOT NULL DEFAULT 'invited'
                  CHECK (status IN ('invited','active','suspended')),
  -- Credentials are NOT stored here by default. auth_subject holds the
  -- external identity-provider subject id, so passwords/MFA/reset flows are
  -- someone else's problem. If we ever roll our own, add password_hash in a
  -- later migration rather than repurposing this column.
  auth_subject  TEXT UNIQUE,
  created_at    TEXT NOT NULL,
  last_login_at TEXT
);

-- Which partners a user may act on, and in what capacity.
--   owner  — it is their own ministry: full read/write on that partner
--   assist — helping out: read, and log interactions, but not delete
--   view   — read only
CREATE TABLE partner_users (
  partner_id  TEXT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  user_id     TEXT NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
  role        TEXT NOT NULL CHECK (role IN ('owner','assist','view')),
  granted_by  TEXT REFERENCES users(id),
  granted_at  TEXT NOT NULL,
  PRIMARY KEY (partner_id, user_id)
);
CREATE INDEX idx_partner_users_user ON partner_users(user_id);

-- Revocable sessions. The existing HMAC token scheme is self-validating and
-- needs no table, but that also means a leaked token cannot be killed before
-- it expires. Once other people's data is involved, revocation stops being
-- optional.
CREATE TABLE sessions (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  issued_at   TEXT NOT NULL,
  expires_at  TEXT NOT NULL,
  revoked_at  TEXT,
  user_agent  TEXT,
  ip          TEXT
);
CREATE INDEX idx_sessions_user    ON sessions(user_id);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);

-- Partner API keys for the read API that chaseroush.com consumes at BUILD
-- time. Scoped to one partner and revocable. Only the hash is stored, so a
-- database leak does not hand over working keys.
CREATE TABLE api_keys (
  id            TEXT PRIMARY KEY,
  partner_id    TEXT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  key_hash      TEXT NOT NULL UNIQUE,
  scopes        TEXT NOT NULL DEFAULT 'read:public',
  created_by    TEXT REFERENCES users(id),
  created_at    TEXT NOT NULL,
  last_used_at  TEXT,
  revoked_at    TEXT
);
CREATE INDEX idx_api_keys_partner ON api_keys(partner_id);


-- ============================================================================
-- CONTACTS — relationship records, NOT financial records
-- ============================================================================
-- This is a stewardship tool: who they are and when we last actually spoke.
-- It holds no amounts and no payment data by design.
CREATE TABLE contacts (
  id            TEXT PRIMARY KEY,
  partner_id    TEXT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,

  first_name    TEXT,
  last_name     TEXT,
  email         TEXT COLLATE NOCASE,
  phone         TEXT,

  -- Postal, for physical newsletters and thank-you notes
  address_1     TEXT,
  address_2     TEXT,
  city          TEXT,
  region        TEXT,
  postal_code   TEXT,
  country       TEXT,                          -- ISO-3166-1 alpha-2

  -- Link out to the giving platform's record. An identifier ONLY — never an
  -- amount, never a payment method.
  giving_ref    TEXT,

  -- Consent is per-purpose. Giving does NOT imply either of these.
  newsletter_consent        INTEGER NOT NULL DEFAULT 0 CHECK (newsletter_consent IN (0,1)),
  newsletter_consent_source TEXT,              -- 'web_form','import','verbal','event'
  newsletter_consent_at     TEXT,
  postal_consent            INTEGER NOT NULL DEFAULT 0 CHECK (postal_consent IN (0,1)),

  -- Freeform stewardship notes. Treat as personal data under GDPR: it is
  -- disclosable to the subject on a access request, so write accordingly.
  notes         TEXT,

  status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active','archived','deleted')),
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
CREATE INDEX idx_contacts_partner       ON contacts(partner_id, status);
CREATE INDEX idx_contacts_partner_email ON contacts(partner_id, email);
CREATE INDEX idx_contacts_newsletter    ON contacts(partner_id, newsletter_consent)
  WHERE newsletter_consent = 1;


-- ============================================================================
-- INTERACTIONS — the contact log
-- ============================================================================
-- is_personal is the whole point of this table. A newsletter going out to 400
-- people is contact, but it is not *personal* contact, and a dashboard that
-- conflates the two will quietly report that everyone has been looked after
-- when nobody has been called in four months.
--
-- "Last personal contact" is DERIVED from this table (see the view below),
-- never stored on contacts. A stored column goes stale the moment something is
-- logged out of order.
CREATE TABLE interactions (
  id            TEXT PRIMARY KEY,
  contact_id    TEXT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  -- Denormalised so every tenant-owned table can be scoped without a join.
  -- Kept honest by trg_interactions_partner_match below.
  partner_id    TEXT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,

  type          TEXT NOT NULL CHECK (type IN (
                  'call','text','email','visit','meal','video_call',
                  'handwritten','newsletter','postal_mail','event','other')),
  -- 1 = a real one-to-one touch. 0 = bulk send or automated.
  is_personal   INTEGER NOT NULL CHECK (is_personal IN (0,1)),
  channel       TEXT NOT NULL DEFAULT 'digital' CHECK (channel IN ('digital','physical','in_person')),

  occurred_on   TEXT NOT NULL,                 -- date; backdating is expected
  note          TEXT,
  logged_by     TEXT REFERENCES users(id),
  -- Set when a bulk send generated this row, so newsletter history appears in
  -- the same timeline as personal touches without being counted as personal.
  source        TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','newsletter','import')),
  created_at    TEXT NOT NULL
);
CREATE INDEX idx_interactions_contact  ON interactions(contact_id, occurred_on DESC);
CREATE INDEX idx_interactions_partner  ON interactions(partner_id, occurred_on DESC);
CREATE INDEX idx_interactions_personal ON interactions(partner_id, is_personal, occurred_on DESC);

-- A newsletter can never be personal contact, whatever the UI sends.
CREATE TRIGGER trg_interactions_bulk_not_personal
BEFORE INSERT ON interactions
FOR EACH ROW WHEN NEW.type IN ('newsletter') AND NEW.is_personal = 1
BEGIN
  SELECT RAISE(ABORT, 'newsletter interactions cannot be marked personal');
END;

-- An interaction must belong to the same partner as its contact. Without this,
-- a bug in the app layer could file Chase's phone call under someone else.
CREATE TRIGGER trg_interactions_partner_match
BEFORE INSERT ON interactions
FOR EACH ROW WHEN NEW.partner_id <> (SELECT partner_id FROM contacts WHERE id = NEW.contact_id)
BEGIN
  SELECT RAISE(ABORT, 'interaction.partner_id must match contact.partner_id');
END;


-- ============================================================================
-- GOALS AND AGGREGATES — the only place money appears
-- ============================================================================
CREATE TABLE goals (
  id            TEXT PRIMARY KEY,
  partner_id    TEXT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  label         TEXT NOT NULL,                 -- 'Monthly support'
  kind          TEXT NOT NULL CHECK (kind IN ('monthly','one_time','project')),
  target_cents  INTEGER NOT NULL CHECK (target_cents > 0),
  currency      TEXT NOT NULL DEFAULT 'USD',
  -- The campaign this goal mirrors on the giving platform. We READ from it.
  -- We never write, and we never process a payment.
  external_ref  TEXT,
  starts_on     TEXT,
  ends_on       TEXT,
  -- Whether the public site may render this goal's numbers.
  is_public     INTEGER NOT NULL DEFAULT 0 CHECK (is_public IN (0,1)),
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
CREATE INDEX idx_goals_partner ON goals(partner_id);

-- ---------------------------------------------------------------------------
-- AGGREGATES ONLY. Read this before adding a column.
-- ---------------------------------------------------------------------------
-- Four numbers, pulled from the giving platform's API. No names, no emails, no
-- amounts-per-person, no payment methods, no transaction ids.
--
-- If you are ever tempted to add donor_name or amount_cents here: that single
-- change turns this database from "holds goal progress" into "holds donor
-- records", and drags in GDPR data-subject obligations, PCI-adjacent scrutiny,
-- breach exposure, and the exact access problem this design exists to avoid.
-- Link out to the giving platform instead.
-- ---------------------------------------------------------------------------
CREATE TABLE goal_snapshots (
  id            TEXT PRIMARY KEY,
  goal_id       TEXT NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
  partner_id    TEXT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  raised_cents  INTEGER NOT NULL CHECK (raised_cents >= 0),
  donor_count   INTEGER CHECK (donor_count >= 0),
  source        TEXT NOT NULL CHECK (source IN ('donorbox','amplify','ministrylinq','manual','other')),
  captured_at   TEXT NOT NULL
);
CREATE INDEX idx_snapshots_goal ON goal_snapshots(goal_id, captured_at DESC);


-- ============================================================================
-- AUDIT LOG — accountability, since technical prevention is impossible
-- ============================================================================
-- Whoever holds the database credentials can read the database. No schema
-- prevents that. What a schema CAN do is make access deliberate, logged, and
-- visible to the partner whose data it is. Append-only by convention; the
-- update/delete triggers make it append-only in fact.
CREATE TABLE audit_log (
  id          TEXT PRIMARY KEY,
  at          TEXT NOT NULL,
  user_id     TEXT REFERENCES users(id),
  partner_id  TEXT REFERENCES partners(id),
  action      TEXT NOT NULL,                   -- 'read','create','update','delete','export','login'
  entity      TEXT NOT NULL,                   -- 'contacts','goals','interactions',…
  entity_id   TEXT,
  detail      TEXT,                            -- JSON blob; never put PII in here
  ip          TEXT
);
CREATE INDEX idx_audit_partner ON audit_log(partner_id, at DESC);
CREATE INDEX idx_audit_user    ON audit_log(user_id, at DESC);

CREATE TRIGGER trg_audit_no_update
BEFORE UPDATE ON audit_log
BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;

CREATE TRIGGER trg_audit_no_delete
BEFORE DELETE ON audit_log
BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;


-- ============================================================================
-- VIEWS — derive, never store
-- ============================================================================
-- The two numbers a stewardship dashboard actually needs. Computed, so they
-- cannot go stale and cannot disagree with the log.
CREATE VIEW contact_touch AS
SELECT
  c.id                AS contact_id,
  c.partner_id        AS partner_id,
  MAX(i.occurred_on)  AS last_contact_any,
  MAX(CASE WHEN i.is_personal = 1 THEN i.occurred_on END) AS last_personal_contact,
  COUNT(i.id)         AS interaction_count,
  SUM(CASE WHEN i.is_personal = 1 THEN 1 ELSE 0 END)      AS personal_count
FROM contacts c
LEFT JOIN interactions i ON i.contact_id = c.id
WHERE c.status = 'active'
GROUP BY c.id, c.partner_id;

-- Latest snapshot per goal, with progress already worked out.
CREATE VIEW goal_progress AS
SELECT
  g.id            AS goal_id,
  g.partner_id    AS partner_id,
  g.label         AS label,
  g.kind          AS kind,
  g.target_cents  AS target_cents,
  g.currency      AS currency,
  g.is_public     AS is_public,
  s.raised_cents  AS raised_cents,
  s.donor_count   AS donor_count,
  s.captured_at   AS captured_at,
  CASE WHEN g.target_cents > 0
       THEN MIN(100, CAST(s.raised_cents * 100.0 / g.target_cents AS INTEGER))
       ELSE 0 END AS percent
FROM goals g
LEFT JOIN goal_snapshots s
  ON s.id = (SELECT id FROM goal_snapshots
             WHERE goal_id = g.id ORDER BY captured_at DESC LIMIT 1);
