-- 0019_markdown_body.sql — what somebody actually wrote
--
-- The composer stored generated HTML, because a contenteditable box has no
-- other form to give you. That editor is gone: it ran on document.execCommand,
-- which is a swamp of cursor and selection bugs and — worse — cannot be tested
-- at all, since neither execCommand nor queryCommandState exists in jsdom. It
-- was replaced with Markdown in a plain textarea, which has no cursor problems
-- to have and converts through a pure function anybody can test.
--
-- SO THE SOURCE IS NOW THE MARKDOWN, and body_html becomes derived. That is
-- the right way round for a second reason: HTML generated by a browser is a
-- lossy record of intent. Reopening a draft used to mean reading back whatever
-- markup the browser happened to emit; now it means reading back the words as
-- typed, character for character.
--
-- body_html is KEPT rather than dropped. It is what the archive renders and
-- what a sent mailing is a record of, and a sent mailing must never change
-- because the converter improved.

ALTER TABLE mailings ADD COLUMN body_md TEXT;
