/**
 * worker.js — the single entry point
 *
 * Everything Netlify did with a directory of functions plus an edge function
 * plus a redirects file is one router here.
 *
 * ROUTING ORDER MATTERS AND IS DELIBERATE:
 *   1. API routes are claimed FIRST and explicitly.
 *   2. "/" exactly is the geo language redirect.
 *   3. Everything else falls through to static assets.
 *
 * Anything not listed in ROUTES is served from _site. That default is the
 * safe one: a typo in a route name means a 404, not an unauthenticated
 * handler answering a path it should not.
 *
 * /staff* IS GATED HERE, IN CODE — not left to an Access application being
 * correctly scoped.
 *
 * Learned the hard way on 2026-08-15: this Worker was deployed to
 * next.thauma.one while the Access application covered dev.thauma.one only.
 * The staff pages AND /staff/data/snapshot.json — supporter names, emails and
 * contact history — were served to anyone who asked. It was seed data, so
 * nothing real leaked, but the mechanism was exactly right.
 *
 * The same mistake was already documented one layer down, in access.js: an
 * endpoint that is only safe because of a routing rule somewhere else is one
 * dashboard edit away from being public. A new hostname is a dashboard edit.
 *
 * So the Worker refuses /staff* itself. Add an Access application in front for
 * defence in depth and a real login page — but the Worker is safe without it.
 */
import langRedirect from "./lang-redirect.js";
import gameScores from "./game-scores.js";
import staffData from "./staff-data.js";
import contactForm from "./contact-form.js";
import partnerApi from "./partner-api.js";
import { createDb, partnerSnapshot, assertPublicSafe } from "./lib/db.js";
import { requireAccess } from "./lib/access.js";
import { json } from "./lib/store.js";

// Runs once per isolate, at module load. If a public query has grown a join
// onto `contacts`, this throws and the deploy fails loudly instead of quietly
// serving supporter records to chaseroush.com. The tests assert the same
// thing, but tests are run by people and this is run by the runtime.
assertPublicSafe();

/**
 * Live replacement for /staff/data/snapshot.json.
 *
 * The console currently fetches a file generated by db/build_snapshot.py.
 * This returns the same shape from D1, so switching the console over is a
 * change to one URL. Gated: it carries supporter names and contact history.
 */
async function staffSnapshot(request, env) {
  const { user, denied } = await requireAccess(request, env);
  if (denied) return denied;

  if (!env.DB) return json({ error: "No database bound to this deploy" }, 500);

  const db = createDb(env.DB);

  // Which partner is this person allowed to see? Access says WHO they are;
  // the database decides WHAT they may read. Never trust a partner id from
  // the query string.
  //
  // Looked up by EMAIL: Access knows email addresses, not our internal user
  // ids. See partners_for_user in db/queries.sql.
  const partners = await db.query("partners_for_user", { email: user.email });
  if (!partners.length) {
    return json({
      error: "No partner access for this account",
      email: user.email,
      hint: "This account authenticated, but no active user row grants it a " +
            "partner. Add the address to `users` and grant it in `partner_users`.",
    }, 403);
  }

  const snap = await partnerSnapshot(db, partners[0].id);
  return json({ ...snap, partner: partners[0], generated_at: new Date().toISOString() });
}

/** Exact-path routes. Checked before static assets. */
const ROUTES = {
  "/api/contact": contactForm,
  "/api/game-scores": gameScores,
  "/api/staff-data": staffData,
  "/api/staff-snapshot": { fetch: staffSnapshot },

  // THE ONLY ROUTE A CREDENTIAL OUTSIDE THAUMA CAN REACH. Key-authenticated,
  // public-safe by construction, versioned in the path so a breaking change
  // becomes /v2 rather than a broken partner site. See partner-api.js.
  "/api/partner/v1/site": partnerApi,

  // Netlify-style paths kept alive so nothing has to change on the same day
  // hosting does. Remove once the front end has moved to /api/*.
  "/.netlify/functions/game-scores": gameScores,
  "/.netlify/functions/staff-data": staffData,
};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // www -> apex, permanently. Netlify did this until the 2026-08-15 cutover;
    // doing it here means www stops depending on a host we are leaving, and
    // the Netlify site can be archived without breaking it.
    //
    // Before the language redirect, so www.thauma.one/ makes ONE hop to
    // thauma.one/ and lands on /en/ from there rather than bouncing twice.
    // Path and query are preserved: a shared link to www.thauma.one/en/give/
    // must arrive at the same page, not the home page.
    if (url.hostname.startsWith("www.")) {
      url.hostname = url.hostname.slice(4);
      return Response.redirect(url.toString(), 301);
    }

    const route = ROUTES[url.pathname];
    if (route) return route.fetch(request, env, ctx);

    // Only the bare root redirects by language. /en/, /hr/ and every asset
    // beneath them must fall through, or the site would redirect forever.
    if (url.pathname === "/") return langRedirect.fetch(request, env, ctx);

    // Everything under /staff — pages, CSS, and crucially the snapshot JSON —
    // requires a valid Access token. Fails closed: no token, no config, or a
    // token for a different application all mean 401.
    if (url.pathname === "/staff" || url.pathname.startsWith("/staff/")) {
      const { denied } = await requireAccess(request, env);
      if (denied) return denied;
    }

    return env.ASSETS.fetch(request);
  },
};
