/**
 * worker.js — the single entry point
 *
 * Everything Netlify did with a directory of functions plus an edge function
 * plus a redirects file is one router here.
 *
 * ROUTING ORDER MATTERS AND IS DELIBERATE:
 *   1. API routes are claimed FIRST and explicitly.
 *   2. "/" exactly is the geo language redirect.
 *   3. Everything else falls through to static assets.
 *
 * Anything not listed in ROUTES is served from _site. That default is the
 * safe one: a typo in a route name means a 404, not an unauthenticated
 * handler answering a path it should not.
 *
 * /staff* IS GATED HERE, IN CODE — not left to an Access application being
 * correctly scoped.
 *
 * Learned the hard way on 2026-08-15: this Worker was deployed to
 * next.thauma.one while the Access application covered dev.thauma.one only.
 * The staff pages AND /staff/data/snapshot.json — supporter names, emails and
 * contact history — were served to anyone who asked. It was seed data, so
 * nothing real leaked, but the mechanism was exactly right.
 *
 * The same mistake was already documented one layer down, in access.js: an
 * endpoint that is only safe because of a routing rule somewhere else is one
 * dashboard edit away from being public. A new hostname is a dashboard edit.
 *
 * So the Worker refuses /staff* itself. Add an Access application in front for
 * defence in depth and a real login page — but the Worker is safe without it.
 */
import langRedirect from "./lang-redirect.js";
import gameScores from "./game-scores.js";
import staffData from "./staff-data.js";
import contactForm from "./contact-form.js";
import partnerApi from "./partner-api.js";
import staffMilestones from "./staff-milestones.js";
import staffSettings from "./staff-settings.js";
import staffGoals from "./staff-goals.js";
import staffPrayer from "./staff-prayer.js";
import staffMailing from "./staff-mailing.js";
import confirmSubscription from "./confirm.js";
import unsubscribe from "./unsubscribe.js";
import archive from "./archive.js";
import signup from "./signup.js";
import contact from "./contact.js";
import adminApi from "./admin.js";
import adminContent from "./admin-content.js";
import adminPublish from "./admin-publish.js";
import adminMigrate from "./admin-migrate.js";
import embed from "./embed.js";
import staffEmbed from "./staff-embed.js";
import adminActAs from "./admin-actas.js";
import adminProfile from "./admin-profile.js";
import staffVideos from "./staff-videos.js";
import adminDbSync from "./admin-dbsync.js";
import confirmAccount from "./confirm-account.js";
import confirmEmail from "./confirm-email.js";
import staffAccount from "./staff-account.js";
import media, { serve as serveMedia } from "./media.js";
import { createDb, partnerSnapshot, assertPublicSafe } from "./lib/db.js";
import { syncAll } from "./lib/video-sync.js";
import { requireAccess } from "./lib/access.js";
import { resolveActor, withActing } from "./lib/actas.js";
import { json } from "./lib/store.js";

// Runs once per isolate, at module load. If a public query has grown a join
// onto `contacts`, this throws and the deploy fails loudly instead of quietly
// serving supporter records to chaseroush.com. The tests assert the same
// thing, but tests are run by people and this is run by the runtime.
assertPublicSafe();

/**
 * Live replacement for /staff/data/snapshot.json.
 *
 * The console currently fetches a file generated by db/build_snapshot.py.
 * This returns the same shape from D1, so switching the console over is a
 * change to one URL. Gated: it carries supporter names and contact history.
 */
async function staffSnapshot(request, env) {
  const { user, denied } = await requireAccess(request, env);
  if (denied) return denied;

  if (!env.DB) return json({ error: "No database bound to this deploy" }, 500);

  const db = createDb(env.DB);

  // Which partner is this person allowed to see? Access says WHO they are;
  // the database decides WHAT they may read. Never trust a partner id from
  // the query string.
  //
  // Looked up by EMAIL: Access knows email addresses, not our internal user
  // ids. See partners_for_user in db/queries.sql.
  // Who this counts as: normally the signed-in person, or the person an
  // administrator is currently viewing. See lib/actas.js.
  const actor = await resolveActor(request, env, db, user);

  const partners = await db.query("partners_for_user", { email: actor.email });
  if (!partners.length) {
    return json(withActing({
      error: "No partner access for this account",
      email: actor.email,
      hint: "This account authenticated, but no active user row grants it a " +
            "partner. Add the address to `users` and grant it in `partner_users`.",
    }, actor), 403);
  }

  const snap = await partnerSnapshot(db, partners[0].id);
  return json(withActing(
    { ...snap, partner: partners[0], generated_at: new Date().toISOString() }, actor));
}


/**
 * A refused PAGE gets a sign-in page. A refused API call still gets JSON.
 *
 * THE BUG THIS FIXES, found 2026-08-16: visiting /admin/ returned the bare
 * string {"error":"Not authorized"} in the browser window. No explanation, no
 * link, nothing to click — "not authorized with no way to authorize", which is
 * exactly how it was reported.
 *
 * The cause is that Cloudflare Access applications are PATH-SCOPED and the
 * application covers `staff`. So /staff/ is intercepted at the edge and gets a
 * real login, while /admin/ is not intercepted at all — the request arrives
 * here with no token, and this Worker's own gate refuses it. The runbook warned
 * about exactly this and it happened anyway, which is a good argument for the
 * Worker not depending on the dashboard being right.
 *
 * The correct fix is to widen the Access application. This exists so that when
 * it is wrong — or a session simply expires — somebody gets a door instead of a
 * error message in JSON.
 *
 * ONLY FOR PAGES. An API route returning a redirect or an HTML body would break
 * every fetch() in the console silently, and those callers handle 401 properly
 * already.
 */
function signInPage(request, env, url) {
  const wantsHtml = (request.headers.get("accept") || "").includes("text/html");
  if (!wantsHtml) return null;

  /* THE BUTTON GOES TO /staff/, NOT TO A CONSTRUCTED LOGIN URL.
     
     The obvious implementation is a link to
     /cdn-cgi/access/login/<hostname>?redirect_url=… — and building it needs a
     hostname this code cannot reliably know. Measured 2026-08-16: under
     `wrangler dev` BOTH url.hostname and the Host header come back as the
     route in wrangler.toml (next.thauma.one) whatever the browser asked for,
     so the link would send somebody to a different site's sign-in page.

     /staff/ is covered by an Access application, so visiting it triggers a
     real login. Access then sets CF_Authorization across the parent domain,
     and this Worker verifies that token itself on every path — so once signed
     in, /admin/ works too. A relative link cannot point at the wrong host.

     One extra click, and it is correct on every hostname without knowing which
     one it is on. */

  const body = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sign in &middot; Thauma</title>
<style>
  body{margin:0;min-height:100vh;display:flex;align-items:center;
       justify-content:center;background:#0B0F15;color:#EDF2F8;
       font-family:system-ui,-apple-system,'Segoe UI',sans-serif;padding:24px}
  .card{max-width:440px;width:100%}
  .mark{font-size:13px;letter-spacing:3px;color:#8A96A6;margin-bottom:20px}
  h1{font-size:24px;font-weight:300;margin:0 0 12px;line-height:1.3}
  p{color:#8A96A6;font-size:14px;line-height:1.7;margin:0 0 20px}
  a.btn{display:inline-block;background:#2FD8FF;color:#06110c;padding:13px 26px;
        border-radius:8px;text-decoration:none;font-weight:600;font-size:15px}
  a.alt{color:#2FD8FF;font-size:13px;text-decoration:none}
  .note{margin-top:28px;padding-top:20px;border-top:1px solid rgba(255,255,255,.08);
        font-size:12px;color:#6b7785;line-height:1.7}
</style></head>
<body><div class="card">
  <div class="mark">THAUMA</div>
  <h1>You need to sign in</h1>
  <p>This part of the site is for staff. Signing in sends a one-time code to
     your email address &mdash; there is no password.</p>
  <p><a class="btn" href="/staff/">Sign in</a></p>
  <div class="note">
    <b>Administrators:</b> if you were sent here from <code>/admin/</code>, the
    Cloudflare Access application is scoped to <code>staff</code> and does not
    cover <code>admin</code>. Sign in above, then return &mdash; or clear the
    path on the Access application so it covers the whole site and this stops
    happening.
  </div>
</div></body></html>`;

  return new Response(body, {
    status: 401,
    headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" },
  });
}

/**
 * Paths that require a signed-in person. THE ONLY DEFINITION.
 *
 * Both areas are gated identically, deliberately and testably. They were
 * already two clauses of one `if`, which is the same thing until somebody
 * edits one clause; a named list with a test that compares the two is the
 * version that stays true.
 *
 * Access authenticates; it does not authorise. Being let through here means
 * "we know who you are", nothing more — /api/admin* separately refuses anyone
 * without the admin role. The pages are markup; the data is what matters.
 *
 * ⚠ THIS IS NOT A SUBSTITUTE FOR THE ACCESS APPLICATION, and it is not
 * redundant with it either. Access gives a real login page; this gives a
 * guarantee. On 2026-08-16 the Access application covered `staff` and not
 * `admin`, so /admin/ was never intercepted — this check is why it was refused
 * anyway instead of being served to anyone who asked.
 */
export function isProtected(pathname) {
  return AREAS.some((a) => pathname === a || pathname.startsWith(a + "/"));
}

const AREAS = ["/staff", "/admin"];

/** Exact-path routes. Checked before static assets. */
const ROUTES = {
  "/api/contact": contactForm,
  "/api/game-scores": gameScores,
  "/api/staff-data": staffData,
  "/api/staff-snapshot": { fetch: staffSnapshot },
  "/api/staff-milestones": staffMilestones,
  "/api/staff-settings": staffSettings,

  // ORG-WIDE, and the only endpoint that is not partner-scoped. Its role
  // check is done once at the top of the handler and fails closed.
  "/api/admin": adminApi,

  // Giving goals: their definition, and progress entered by hand for a
  // partner whose platform has no integration. See staff-goals.js.
  "/api/staff-goals": staffGoals,

  // Prayer requests and their answers. Same shape as milestones — a state row
  // and one translation per language. See staff-prayer.js.
  "/api/staff-prayer": staffPrayer,

  // A partner's own mailing lists. Scoped to them; see staff-mailing.js.
  "/api/staff-mailing": staffMailing,

  // Which YouTube channel or playlist a partner's site shows videos from. The
  // videos themselves are fetched by the scheduled handler below, from a
  // public feed that needs no key. See staff-videos.js.
  "/api/staff-videos": staffVideos,

  // Public, no account. The link in a mailing list confirmation email.
  "/confirm": confirmSubscription,

  /* An invited person turning their own account on. PUBLIC, and it must stay
     that way: this is the page somebody visits before they can sign in, so
     gating it would mean needing an account to confirm your account. The
     signature in the link is the credential. See confirm-account.js. */
  "/confirm-account": confirmAccount,

  /* Finishing a change of sign-in address. Public for the same reason as the
     line above, and one sharper: the person is proving they can read the NEW
     inbox, possibly on a device that has never signed in. See
     confirm-email.js. */
  "/confirm-email": confirmEmail,

  /* Starting one. Authenticated, and it deliberately ignores "acting as" —
     changing who you are is not something done on somebody's behalf. */
  "/api/staff-account": staffAccount,

  /* Public, no account, and it must stay that way: a reader who cannot find
     the way out presses "report spam" instead, and that damages the sending
     domain for everybody else the ministry writes to. */
  "/unsubscribe": unsubscribe,

  // THE ONLY ENDPOINT THAT CAN WRITE TO THE REPOSITORY. It holds a GitHub
  // token, so a save here becomes a commit and the Action deploys it. Admin
  // role, a derived path that no request can influence, and leaf-level edits
  // only — see admin-content.js.
  "/api/admin/content": adminContent,

  // Asks GitHub to build the live branch — for staging (Preview) or for the
  // real site (Publish). Saving already committed the words with [skip ci], so
  // this is the only thing that moves the site, and it lists what it is about
  // to ship and takes a typed confirmation. See admin-publish.js.
  "/api/admin/publish": adminPublish,

  // The embed payload for the console's own preview. Same builder as the
  // public route, but for the caller's OWN partner and whether or not
  // embedding is switched on — so you can look before you decide to publish.
  "/api/staff-embed": staffEmbed,

  // Applies database migrations from the repository to the bound D1. The only
  // part of running this site that still needed a terminal. Reads the SQL from
  // the live branch, so everything it can execute has been through a diff —
  // there is no arbitrary SQL box. See admin-migrate.js.
  "/api/admin/migrate": adminMigrate,

  // Start and stop viewing somebody else's console. Sets a cookie that names
  // a user id and grants nothing — authority is re-derived from the Access
  // token on every request. See lib/actas.js.
  "/api/admin/act-as": adminActAs,

  // The public half of a person, edited from the People page. Writes the
  // database AND src/content/team/<slug>.md — see admin-profile.js.
  "/api/admin/profile": adminProfile,

  // Moves ROWS between this deployment and staging, from a button rather than
  // a terminal. Offered only where a D1 credential is configured, which is the
  // development site and nowhere else. See admin-dbsync.js.
  "/api/admin/db-sync": adminDbSync,

  // Uploads. GET /media/* is handled by prefix below, not here.
  "/api/admin/media": media,

  // THE ONLY ROUTE A CREDENTIAL OUTSIDE THAUMA CAN REACH. Key-authenticated,
  // public-safe by construction, versioned in the path so a breaking change
  // becomes /v2 rather than a broken partner site. See partner-api.js.
  "/api/partner/v1/site": partnerApi,

  // Netlify-style paths kept alive so nothing has to change on the same day
  // hosting does. Remove once the front end has moved to /api/*.
  "/.netlify/functions/game-scores": gameScores,
  "/.netlify/functions/staff-data": staffData,
};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // www -> apex, permanently. Netlify did this until the 2026-08-15 cutover;
    // doing it here means www stops depending on a host we are leaving, and
    // the Netlify site can be archived without breaking it.
    //
    // Before the language redirect, so www.thauma.one/ makes ONE hop to
    // thauma.one/ and lands on /en/ from there rather than bouncing twice.
    // Path and query are preserved: a shared link to www.thauma.one/en/give/
    // must arrive at the same page, not the home page.
    if (url.hostname.startsWith("www.")) {
      url.hostname = url.hostname.slice(4);
      return Response.redirect(url.toString(), 301);
    }

    const route = ROUTES[url.pathname];
    if (route) return route.fetch(request, env, ctx);

    /* THE ONLY UNAUTHENTICATED, CROSS-ORIGIN ROUTE, and a prefix rather than
       an exact path because the slug is in it. Before the auth gate below,
       and it must stay there: an embed runs in a stranger's browser on a site
       we do not control, so there is no session to check and nothing to sign
       in to. What makes that safe is per-partner opt-in, not a gate — see
       embed.js. */
    /* The sign-up form and what it posts to, under the embed origin so a
       partner's page loads it the same way it loads the widgets. Matched
       BEFORE the embed router, which owns everything else under this path. */
    const signupPath = url.pathname.match(
      /^\/embed\/v1\/([a-z0-9-]+)\/(form\.js|signup)$/);
    if (signupPath) {
      return signup.fetch(request, env, signupPath[1], signupPath[2]);
    }

    /* The contact form, alongside the sign-up form and matched the same way.
       Two public forms, one look — see lib/embed-form.js. */
    const contactPath = url.pathname.match(
      /^\/embed\/v1\/([a-z0-9-]+)\/(contact\.js|contact)$/);
    if (contactPath) {
      return contact.fetch(request, env, contactPath[1], contactPath[2]);
    }

    if (url.pathname.startsWith("/embed/v1/")) return embed.fetch(request, env, ctx);

    /* Past newsletters, linked from the footer of every mailing. Only lists
       marked public appear — newsletters are meant to be read, prayer updates
       name people and are not. */
    const archivePath = url.pathname.match(
      /^\/archive\/([a-z0-9-]+)\/([a-z0-9-]+)(?:\/([a-z0-9-]+))?\/?$/);
    if (archivePath) {
      return archive.fetch(request, env, archivePath[1], archivePath[2], archivePath[3]);
    }

    /* Uploaded files. A prefix rather than a table entry because the rest of
       the path IS the object key. Public and unauthenticated on purpose — a
       staff photo is printed on the public team page, so requiring a session
       to fetch it would break the page it exists for. */
    if (url.pathname.startsWith("/media/")) {
      return serveMedia(request, env, url.pathname.slice("/media/".length));
    }

    // Only the bare root redirects by language. /en/, /hr/ and every asset
    // beneath them must fall through, or the site would redirect forever.
    if (url.pathname === "/") return langRedirect.fetch(request, env, ctx);

    // ONE gate, ONE list. /staff and /admin are protected identically and by
    // the same code — see isProtected().
    if (isProtected(url.pathname)) {
      const { denied } = await requireAccess(request, env);
      if (denied) return signInPage(request, env, url) || denied;
    }

    return env.ASSETS.fetch(request);
  },

  /**
   * THE ONLY SCHEDULED WORK IN THIS WORKER, and the replacement for Netlify's
   * schedule() wrapper that chaseroush.com used for the same job.
   *
   * Every quarter hour it re-reads the public Atom feed of each switched-on
   * source — a channel, or a playlist. That is ninety-six invocations a day for the whole site — far
   * inside the free allowance, and there is no API key or quota behind it
   * because the feed is public. Deliberately kept that cheap: a scheduled job
   * is the easiest thing in a system to leave running and forget the price of.
   *
   * A cron cannot report to anybody, so it reports to the DATABASE: every
   * channel records its own synced_at and sync_error, and the console shows
   * them. `waitUntil` is not used — the run IS the invocation, and returning
   * before the writes land would lose them.
   */
  async scheduled(event, env, ctx) {
    if (!env.DB) {
      console.error("scheduled run skipped: no database bound");
      return;
    }
    const db = createDb(env.DB);
    const results = await syncAll(db);
    const failed = results.filter((r) => !r.ok);
    console.log(
      `video sync: ${results.length} source(s), ${failed.length} failed`,
      failed.map((f) => `${f.partner_id || "organisation"}: ${f.error}`).join("; "));
  },
};
