#!/usr/bin/env node
/**
 * import_team_profiles.mjs — the existing team markdown, into staff_profiles
 *
 *   node db/import_team_profiles.mjs            # print the SQL
 *   node db/import_team_profiles.mjs --apply    # and run it against dev
 *
 * WHY THIS EXISTS
 * ---------------------------------------------------------------------------
 * The People page edits staff_profiles in D1 and writes src/content/team/*.md
 * on save. That export was built; the IMPORT was not. So a person whose profile
 * predates the console — which is everybody, since the files came from Decap —
 * appeared blank in the editor while their real bio and photo were on the
 * public site the whole time.
 *
 * THAT WAS NOT MERELY COSMETIC. The form saves what it shows. Filling in one
 * field on a profile that looked empty would have written a markdown file with
 * one field in it, over the top of a real one, and the only copy of the lost
 * text would have been in git history.
 *
 * Matched by SLUG, which is the filename and the public URL — the durable
 * identifier here. The user_id in the frontmatter is written by the console on
 * save and is absent from anything Decap produced, so it cannot be relied on
 * for the first import.
 *
 * IDEMPOTENT. Existing rows are left alone rather than overwritten: by the time
 * this is run twice, the database is the newer copy and the file is its output.
 */
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import matter from "../node_modules/gray-matter/index.js";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const DIR = ROOT + "src/content/team/";
const APPLY = process.argv.includes("--apply");

if (!existsSync(DIR)) {
  console.log("No src/content/team/ — nothing to import.");
  process.exit(0);
}

const q = (v) => (v == null || v === "" ? "NULL" : "'" + String(v).replace(/'/g, "''") + "'");

const files = readdirSync(DIR).filter((f) => f.endsWith(".md"));
if (!files.length) {
  console.log("No team files — nothing to import.");
  process.exit(0);
}

const out = [
  "-- Generated by db/import_team_profiles.mjs",
  "-- The team markdown that predates the People page editor, so the editor",
  "-- shows what the public site already shows. INSERT OR IGNORE: a profile",
  "-- already in the database is the newer copy and is left alone.",
  "",
];
let people = 0, translations = 0;

for (const file of files) {
  const slug = file.replace(/\.md$/, "");
  const { data } = matter(readFileSync(DIR + file, "utf8"));

  /* The account this profile belongs to. Matched on the public email first,
     then the person's name — the frontmatter has no user id unless the console
     wrote the file, and on a first import it never has. */
  const email = data.email || null;
  const name = data.name || slug;

  out.push(`-- ---------- ${name} (${slug}) ----------`);
  out.push(
    "INSERT OR IGNORE INTO staff_profiles",
    "  (user_id, is_public, slug, region, public_email, photo, bio_photo,",
    "   sort_order, created_at, updated_at)",
    "SELECT u.id, 1, " + [q(slug), q(data.base), q(email), q(data.photo), q(data.bio_photo)].join(", ") + ",",
    `       ${Number(data.order) || 0}, datetime('now'), datetime('now')`,
    "  FROM users u",
    /* The file existing at all means this person IS on the public site, so
       is_public is 1 above — importing them as unpublished would take the
       team page down the first time somebody pressed Save. */
    ` WHERE lower(u.email) = lower(${q(email)}) OR lower(u.name) = lower(${q(name)})`,
    " LIMIT 1;",
    "",
  );
  people++;

  const langs = new Set([
    ...Object.keys(data.role || {}),
    ...Object.keys(data.bio || {}),
  ]);
  for (const lang of langs) {
    const role = (data.role || {})[lang] || null;
    const bio = (data.bio || {})[lang] || null;
    if (!role && !bio) continue;
    out.push(
      "INSERT OR IGNORE INTO staff_profile_translations",
      "  (user_id, lang, role_title, bio, updated_at)",
      `SELECT sp.user_id, ${q(lang)}, ${q(role)}, ${q(bio)}, datetime('now')`,
      `  FROM staff_profiles sp WHERE sp.slug = ${q(slug)};`,
      "",
    );
    translations++;
  }
}

const sql = out.join("\n");

if (!APPLY) {
  console.log(sql);
  console.error(`\n-- ${people} profile(s), ${translations} translation(s).`);
  console.error("-- Re-run with --apply to write them to the dev database.");
  process.exit(0);
}

const file = ROOT + "db/.import-team.generated.sql";
import("node:fs").then(({ writeFileSync }) => {
  writeFileSync(file, sql + "\n");
  console.log(`Applying ${people} profile(s), ${translations} translation(s) to thauma-ops-dev…`);
  const res = execFileSync("npx", [
    "wrangler", "d1", "execute", "thauma-ops-dev", "--local", "--file", file,
  ], { cwd: ROOT, encoding: "utf8" });
  console.log(/"success": true/.test(res) ? "Done." : res.slice(-400));
});
